use anyhow::{Context, Result};
use common::{
    progress::Progress,
    serde::{Deserializer, Serializer},
};
use nalgebra::Vector3;

use crate::{Mesh, util::tokenize};

pub fn parse<T: Deserializer>(des: &mut T, progress: &Progress) -> Result<Mesh> {
    progress.set_total(des.size() as u64);

    let (mut verts, mut faces) = (Vec::new(), Vec::new());
    tokenize(des, &['\n', '\r'], progress, |line| {
        let mut parts = line.split_whitespace();
        match parts.next() {
            Some("v") => {
                let vert = next_vertex(parts).context("Invalid vertex")?;
                verts.push(vert);
            }
            Some("f") => {
                let face = next_face(parts).context("Invalid face")?;
                faces.push(face);
            }
            _ => {}
        }
        Ok(())
    })?;

    Ok(Mesh {
        verts: verts.into_boxed_slice(),
        faces: faces.into_boxed_slice(),
    })
}

pub fn serialize<T: Serializer>(ser: &mut T, progress: &Progress, mesh: &Mesh) {
    progress.set_total((mesh.verts.len() + mesh.faces.len()) as u64);
    ser.write_bytes(b"# Generated by mslicer\n");

    let normals = mesh.vertex_normals();
    for (vert, normal) in mesh.verts.iter().zip(normals.iter()) {
        ser.write_bytes(format!("v {} {} {}\n", vert.x, vert.y, vert.z).as_bytes());
        ser.write_bytes(format!("vn {} {} {}\n", normal.x, normal.y, normal.z).as_bytes());
        progress.add_complete(1);
    }

    for [a, b, c] in mesh.faces.iter() {
        ser.write_bytes(
            format!(
                "f {a}//{a} {b}//{b} {c}//{c}\n",
                a = a + 1,
                b = b + 1,
                c = c + 1
            )
            .as_bytes(),
        );
        progress.add_complete(1);
    }
}

fn next_vertex<'a>(mut parts: impl Iterator<Item = &'a str>) -> Option<Vector3<f32>> {
    Some(Vector3::new(
        parts.next()?.parse().ok()?,
        parts.next()?.parse().ok()?,
        parts.next()?.parse().ok()?,
    ))
}

fn next_face<'a>(mut parts: impl Iterator<Item = &'a str>) -> Option<[u32; 3]> {
    fn next_idx<'a>(parts: &mut impl Iterator<Item = &'a str>) -> Option<u32> {
        let str = parts.next()?;
        let number = str.split_once('/').map(|x| x.0).unwrap_or(str);
        Some(number.parse::<u32>().ok()? - 1)
    }

    Some([
        next_idx(&mut parts)?,
        next_idx(&mut parts)?,
        next_idx(&mut parts)?,
    ])
}
