use std::collections::HashMap;

use anyhow::Result;
use common::{
    progress::Progress,
    serde::{Deserializer, Serializer},
};
use nalgebra::Vector3;

use crate::{
    Mesh,
    util::{WHITESPACE, tokenize},
};

pub fn parse<T: Deserializer>(des: &mut T, progress: &Progress) -> Result<Mesh> {
    des.advance_by(80);
    let tri_count = des.read_u32_le();
    let is_ascii = des.size() != 84 + 50 * tri_count as usize;
    des.jump_to(0);

    match is_ascii {
        true => ascii::parse(des, progress),
        false => binary::parse(des, progress),
    }
}

pub fn serialize<T: Serializer>(ser: &mut T, progress: &Progress, mesh: &Mesh) {
    // why would you ever use the text format :sob:
    binary::serialize(ser, progress, mesh);
}

/// From Wikipedia :eyes:
/// ```plain
/// UINT8[80]    – Header                 - 80 bytes
/// UINT32       – Number of triangles    - 04 bytes
/// foreach triangle                      - 50 bytes
///     REAL32[3] – Normal vector         - 12 bytes
///     REAL32[3] – Vertex 1              - 12 bytes
///     REAL32[3] – Vertex 2              - 12 bytes
///     REAL32[3] – Vertex 3              - 12 bytes
///     UINT16    – Attribute byte count  - 02 bytes
/// end
/// ```
mod binary {
    use super::*;

    pub fn parse<T: Deserializer>(des: &mut T, progress: &Progress) -> Result<Mesh> {
        des.advance_by(80); // skip header
        let tri_count = des.read_u32_le();
        progress.set_total(tri_count as u64);

        let mut verts = HashMap::new();
        let mut faces = Vec::new();
        for i in 0..tri_count {
            progress.set_complete(i as u64);
            des.advance_by(4 * 3);
            faces.push([
                vert_idx(&mut verts, des_vec3f_bin(des)),
                vert_idx(&mut verts, des_vec3f_bin(des)),
                vert_idx(&mut verts, des_vec3f_bin(des)),
            ]);
            des.advance_by(2);
        }

        Ok(finish(verts, faces.into_boxed_slice()))
    }

    pub fn serialize<T: Serializer>(ser: &mut T, progress: &Progress, mesh: &Mesh) {
        progress.set_total(mesh.faces.len() as u64);

        const HEADER: &[u8] = b"Generated by mslicer.";
        ser.write_bytes(HEADER);
        ser.write_bytes(&[0; 80 - HEADER.len()]);

        ser.write_u32_le(mesh.faces.len() as u32);
        for (i, face) in mesh.faces.iter().enumerate() {
            ser_vec3f_bin(ser, &mesh.face_normal(i));
            face.iter()
                .for_each(|&v| ser_vec3f_bin(ser, &mesh.verts[v as usize]));
            ser.write_u16_le(0);
            progress.add_complete(1);
        }
    }
}

/// ```plain
/// solid name
/// facet normal ni nj nk
///     outer loop
///         vertex v1x v1y v1z
///         vertex v2x v2y v2z
///         vertex v3x v3y v3z
///     endloop
/// endfacet
/// endsolid name
/// ```
mod ascii {
    use super::*;

    pub fn parse<T: Deserializer>(des: &mut T, progress: &Progress) -> Result<Mesh> {
        progress.set_total(des.size() as u64);

        let mut verts = HashMap::new();
        let mut faces = Vec::new();

        let mut builder = [Vector3::zeros(); 3];
        let mut component = 9;

        tokenize(des, &WHITESPACE, progress, |token| {
            if component < 9 {
                let Ok(value) = token.parse::<f32>() else {
                    return Ok(());
                };

                builder[component / 3][component % 3] = value;
                component += 1;
                return Ok(());
            }

            match token {
                "vertex" => component = 0,
                "endloop" => {
                    faces.push([
                        vert_idx(&mut verts, builder[0]),
                        vert_idx(&mut verts, builder[1]),
                        vert_idx(&mut verts, builder[2]),
                    ]);
                }
                _ => {}
            }

            Ok(())
        })?;

        Ok(finish(verts, faces.into_boxed_slice()))
    }
}

fn vert_idx(verts: &mut HashMap<Vector3<u32>, u32>, vert: Vector3<f32>) -> u32 {
    let size = verts.len() as u32;
    *verts.entry(vert.map(f32::to_bits)).or_insert(size)
}

fn finish(verts: HashMap<Vector3<u32>, u32>, faces: Box<[[u32; 3]]>) -> Mesh {
    let mut verts = verts.into_iter().collect::<Vec<_>>();
    verts.sort_by_key(|(_vert, idx)| *idx);
    let verts = (verts.into_iter())
        .map(|(vert, _idx)| vert.map(f32::from_bits))
        .collect();
    Mesh { verts, faces }
}

fn des_vec3f_bin<T: Deserializer>(des: &mut T) -> Vector3<f32> {
    Vector3::new(des.read_f32_le(), des.read_f32_le(), des.read_f32_le())
}

fn ser_vec3f_bin<T: Serializer>(ser: &mut T, vec: &Vector3<f32>) {
    ser.write_f32_le(vec.x);
    ser.write_f32_le(vec.y);
    ser.write_f32_le(vec.z);
}
